[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["John Downey <jdowney@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.4.0"
derive_builder = "0.10.2"
generic-array = "0.14.4"
num = "0.4.0"
ord_subset = "3.1.1"
thiserror = "1.0"
typenum = "1.13"

[dev-dependencies]
anyhow = "1.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
