[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["John Downey <jdowney@gmail.com>"]
edition = "2018"

[dependencies]
approx = "0.3.2"
derive_builder = "0.7.2"
generic-array = "0.13.2"
indextree = "3.3.0"
num-traits = "0.2.8"
rayon = "1.1.0"
typenum = "1.10.0"

[dev-dependencies]
indicatif = "0.11.0"
