[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["John Downey <jdowney@gmail.com>"]
edition = "2018"

[dependencies]
typenum = "1.10.0"
generic-array = "0.12.0"
num-traits = "0.2.6"
itertools = "0.8.0"
