[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.38"

[dev-dependencies]
anyhow = "1.0.69"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
