[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["John Downey <jdowney@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.4.0"
num = "0.4.0"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
